name: newifi3d2-actions

env:
  TZ: Asia/Shanghai

on:
  push:
    branches: 
      - main
  schedule:
    - cron: 0 0 * * 5

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      BIN_PATH: /home/runner/work/immortalwrt-ci/immortalwrt-ci/immortalwrt/bin

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Build Environment Initialization
        run: |
          sudo apt-get update
          sudo apt-get -qq remove --purge mysql* php* google* firefox ghc azure-cli dotnet* powershell ruby-full zulu* llvm*
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /var/lib/docker
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/hostedtoolcache/go /opt/hostedtoolcache/Ruby /opt/hostedtoolcache/node
          sudo apt-get -qq autoremove --purge
          sudo apt-get -qq clean

      - name: Build newifi3d2
        run: |
          chmod +x build-newifi3d2.sh && ./build-newifi3d2.sh

      - name: Upload Packages
        uses: actions/upload-artifact@v3
        with:
          name: Newifi3-d2-Packages
          path: /home/runner/work/immortalwrt-ci/immortalwrt-ci/immortalwrt/bin/packages/

      - name: Upload Firmwares
        uses: actions/upload-artifact@v3
        with:
          name: Newifi3-d2-Firmwares
          path: /home/runner/work/immortalwrt-ci/immortalwrt-ci/immortalwrt/bin/targets/

      - name: Upload manifest
        uses: actions/upload-artifact@v3
        with:
          name: manifest-${{ env.FILE_DATE }}
          path: /home/runner/work/immortalwrt-ci/immortalwrt-ci/immortalwrt/bin/targets/ramips/mt7621/immortalwrt-ramips-mt7621-d-team_newifi-d2.manifest
