name: 360t7-actions

env:
  TZ: Asia/Shanghai

on:
  push:
    branches: 
      - main
  workflow_dispatch:
#  schedule:
#    - cron: 0 0 * * 5

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      BIN_PATH: /home/runner/work/immortalwrt-ci/immortalwrt-ci/immortalwrt/bin

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Build Environment Initialization
        run: |
          sudo apt-get update
          sudo apt-get -qq remove --purge mysql* php* google* firefox ghc azure-cli dotnet* powershell ruby-full zulu* llvm*
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /var/lib/docker
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/hostedtoolcache/go /opt/hostedtoolcache/Ruby /opt/hostedtoolcache/node
          sudo apt-get -qq autoremove --purge
          sudo apt-get -qq clean

      - name: Build 360t7
        run: |
          chmod +x build-360t7.sh && ./build-360t7.sh

      - name: Upload Packages
        uses: actions/upload-artifact@main
        with:
          name: 360t7-Packages
          path: ${{ env.BIN_PATH }}/packages/

      - name: Upload Firmwares
        uses: actions/upload-artifact@main
        with:
          name: 360t7-Firmwares
          path: ${{ env.BIN_PATH }}/targets/

      - name: Upload manifest
        uses: actions/upload-artifact@main
        with:
          name: manifest-${{ env.FILE_DATE }}
          path: ${{ env.BIN_PATH }}/targets/mediatek/filogic/immortalwrt-mediatek-filogic-qihoo_360t7.manifest
